CHANGELOG.md
CMakeLists.txt
docs/dev-guide/edge-agent-dev-guide.md
src/datamanagement/datadecoding/include/OBDDataDecoder.h
src/datamanagement/datadecoding/src/OBDDataDecoder.cpp
src/datamanagement/datadecoding/test/OBDDataDecoderTest.cpp
src/datamanagement/datainspection/include/OBDOverCANModule.h
src/datamanagement/datainspection/src/diag/OBDOverCANModule.cpp
src/datamanagement/datainspection/test/OBDOverCANModuleTest.cpp
src/datamanagement/datamanager/include/CollectionSchemeManager.h
src/datamanagement/datamanager/src/DecoderDictionaryExtractor.cpp
src/datamanagement/datamanager/test/DecoderDictionaryExtractorTest.cpp
src/datamanagement/types/include/OBDDataTypes.h

Release v0.1.4

---

README.md

Updating the API reference link update in the README

API reference link update

---

README.md
configuration/static-config.json
tools/configure-fwe.sh

* Add Important note to readme for legal statement
* Set the default checkin period to 2-min while keeping the quick demo at 5 seconds

set default checkin period to 2-min

---

CHANGELOG.md
CMakeLists.txt
docs/dev-guide/edge-agent-dev-guide.md
docs/rpi-tutorial/raspberry-pi-tutorial.md
src/datamanagement/datacollection/include/DataCollectionProtoWriter.h
src/datamanagement/datacollection/src/DataCollectionProtoWriter.cpp
src/datamanagement/datacollection/test/DataCollectionProtoWriterTest.cpp
src/vehiclenetwork/src/CANDataSource.cpp
src/vehiclenetwork/test/CANDataSourceTest.cpp
tools/cloud/demo.sh
tools/cloud/iotfleetwise-2021-06-17.json

Edge Release V1.0.0

---

tools/cloud/demo.sh

The role creation is now handled by the cloud.

Remove service role check from demo script

---

.git-blame-ignore-revs
.prettierignore

Add format commit to .git-blame-ignore-revs

---

docs/rpi-tutorial/raspberry-pi-tutorial.md

Correct the build instructions in the R-Pi guide

---

docs/dev-guide/edge-agent-dev-guide.md
docs/iwave-g26-tutorial/iwave-g26-tutorial.md
docs/rpi-tutorial/raspberry-pi-tutorial.md
tools/build-dist.sh
tools/cloud/.gitignore
tools/cloud/clean-up.sh
tools/cloud/demo.sh
tools/cloud/install-deps.sh
tools/cloud/s3-to-html.py

Update demo script to support S3 destination

---

docs/dev-guide/edge-agent-dev-guide.md

Update pip command to
1. update dependency versions to be compatible with AWS CloudShell
2. Fix syntax for fastparquet
- Ran the command successfully in CloudShell
Signed-off-by: Krishna Koppolu <kkoppolu@amazon.com>

pip command update

---

src/datamanagement/types/include/Geohash.h
src/offboardconnectivity/implementation/aws/iotcpp/test/src/AwsIotConnectivityModuleTest.cpp
src/platform/linux/logmanagement/include/ConsoleLogger.h
src/platform/linux/logmanagement/include/ILogger.h
src/platform/linux/persistencymanagement/include/CacheAndPersist.h
src/platform/linux/persistencymanagement/include/ICacheAndPersist.h

Request from: https://github.com/aws/aws-iot-fleetwise-edge/issues/47

Add gcc13 compatible imports

---

tools/android-app/cloud/provision.sh
tools/android-app/cloud/setup-iotfleetwise.sh

Fix Android provisioning with bucket region

---

tools/android-app/cloud/provision.sh
tools/cfn-templates/fwdemo.yml

To fix issue https://github.com/aws/aws-iot-fleetwise-edge/issues/55

Fix Android provision cloud script

---

.github/workflows/ci.yml
tools/configure-fwe.sh
tools/container/README.md

This Pull Request contains two changes
1. Update docker container to accept IoT credentials via environment variable.
2. Add main branch to docker build flow. The main branch will be tagged as main in public ECR.

pass cert and key as env var to docker container

---

tools/android-app/README.md
tools/install-deps-cross-arm64.sh
tools/install-deps-cross-armhf.sh

Fix GitHub cross builds

---

src/offboardconnectivity/api/include/ISender.h
src/platform/linux/persistencymanagement/src/CacheAndPersist.cpp

To fix new gcc builds found here https://github.com/aws/aws-iot-fleetwise-edge/issues/61

Add missing headers

---

src/platform/linux/persistencymanagement/src/CacheAndPersist.cpp

Add slash to persistencyFolder if missing

---

tools/cfn-templates/fwdemo.yml
tools/cfn-templates/fwdev.yml

Update Ubuntu AMIs

---

docs/dev-guide/vision-system-data/vision-system-data-demo.ipynb

Improve VSD demo guide

---

README.md
docs/dev-guide/vision-system-data/vision-system-data-demo.ipynb

Improve Jupyter Notebook guide links

---

src/AwsIotChannel.cpp

Fix nullptr exception with invalid credentials

---

docs/iwave-g26-tutorial/iwave-g26-tutorial.md
docs/iwave-g26-tutorial/iwave-gps-setup.md

Correct iWave GPS documentation

---

.github/template/docker-build/action.yml
.github/template/fwe-build/action.yml
.github/workflows/ci.yml

Update GitHub actions to versions using Node v20

---

tools/cloud/dbc-to-decoders.py
tools/cloud/dbc-to-nodes.py

If multiple frames have the same name, add the frame ID as a suffix

Allow permissive DBC parsing

---

.pre-commit-config.yaml
cmake/clang_tidy.cmake
src/ClockHandler.cpp
src/CollectionSchemeIngestion.cpp
src/CollectionSchemeIngestion.h
src/ConsoleLogger.cpp
src/ConsoleLogger.h
src/LogLevel.h
src/PayloadManager.h
src/ROS2DataSource.cpp
src/RemoteProfiler.cpp
src/RemoteProfiler.h
src/RetryThread.cpp
src/RetryThread.h
src/main.cpp
tools/install-deps-native.sh

Update to clang-format and clang-tidy v12

---

tools/android-app/cloud/setup-iotfleetwise.sh

Add timestream:DescribeTable permission to Android script

---

tools/install-deps-cross-android.sh
tools/install-deps-cross-arm64.sh
tools/install-deps-cross-armhf.sh
tools/install-deps-native.sh

To use built in CA store of OpenSSL

Use CA fallback with cURL

---

tools/cfn-templates/fwdev.yml

Add x86_64 support to fwdev.yml

---

tools/install-deps-cross-android.sh
tools/install-deps-cross-arm64.sh
tools/install-deps-cross-armhf.sh

Fix pkg-config when cross compiling curl

---

.github/template/fwe-build/action.yml
tools/test-fwe.sh

Added flag --extra-ctest-args to add tests to skip

---

src/DataSenderProtoWriter.cpp
src/RawDataManager.h

Decrease usage hint after handover to sender

---

docs/dev-guide/can-actuators-dev-guide.md
docs/dev-guide/edge-agent-dev-guide-last-known-state.md
docs/dev-guide/edge-agent-dev-guide-someip.md
tools/cloud/install-deps.sh

Updated packaging version and create-command namespace

---

tools/cfn-templates/fwdemo.yml
tools/cfn-templates/fwdev.yml
tools/cfn-templates/vision-system-data-jupyter.yml

Update Ubuntu 20.04 AMIs

---

tools/cfn-templates/fwdemo.yml
tools/cfn-templates/fwdev.yml
tools/cfn-templates/vision-system-data-jupyter.yml

Update Ubuntu 20.04 AMI

---

tools/cfn-templates/fwdemo.yml
tools/cfn-templates/fwdev.yml
tools/cfn-templates/vision-system-data-jupyter.yml

Use apt-dist upgrade to ensure proper kernel updates

---

CHANGELOG.md
CMakeLists.txt
src/InspectionMatrixExtractor.cpp
src/RemoteDiagnosticDataSource.cpp
test/system/testframework/greengrass.py
tools/cfn-templates/vision-system-data-jupyter.yml
tools/install-deps-cross-arm64.sh
tools/install-deps-cross-armhf.sh

Release v1.3.1

---

configuration/static-config.json
include/aws/iotfleetwise/S3Sender.h
interfaces/protobuf/schemas/edgeConfiguration/staticConfiguration.json
src/IoTFleetWiseEngine.cpp
src/S3Sender.cpp
test/unit/S3SenderTest.cpp
test/unit/support/S3SenderMock.h

Add connection timeout configuration to S3Sender

---

.github/workflows/update-cfn-ami-ids.yml
tools/update-cfn-ami-ids.py

2025 07 08 main add script for ami update
